#!/bin/bash
#
# 20240210 Jens Heine <binbash@gmx.net>
#
WIFI_SSID=${1}

[ -z ${WIFI_SSID} ] && { echo "SSID is missing."; exit 1; }

echo "Creating new wifi connection for SSID: ${WIFI_SSID}"

sudo nmcli connection add type wifi ifname wlan0 ssid ${WIFI_SSID} connection.id ${WIFI_SSID}
sudo nmcli connection modify ${WIFI_SSID} connection.autoconnect 1
sudo nmcli connection modify ${WIFI_SSID} connection.autoconnect-priority 10
sudo nmcli connection modify ${WIFI_SSID} 802-11-wireless-security.key-mgmt wpa-psk
sudo nmcli connection modify ${WIFI_SSID} 802-11-wireless-security.auth-alg open
sudo nmcli connection up --ask ${WIFI_SSID} && nmcli connection show

