#!/bin/bash
#
# 20240210 Jens Heine <binbash@gmx.net>
#
sudo="sudo -h 127.0.0.1"
WIFI_SSID="${1}"
WIFI_PASSWORD_FILE="/home/p/wifi_password"

[ ! "${WIFI_SSID}" ] && { echo "Error: The SSID of the wifi network is missing."; exit 1; }

echo
echo "> Creating new wifi connection for SSID: "${WIFI_SSID}""
read -p "> Enter wifi password for '${WIFI_SSID}': " WIFI_PASSWORD
echo
echo "802-11-wireless-security.psk:"${WIFI_PASSWORD}""  > "${WIFI_PASSWORD_FILE}"

$sudo nmcli connection add type wifi ifname wlan0 ssid "${WIFI_SSID}" connection.id "${WIFI_SSID}"
$sudo nmcli connection modify "${WIFI_SSID}" connection.autoconnect 1
$sudo nmcli connection modify "${WIFI_SSID}" connection.autoconnect-priority 10
$sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless.powersave 2
$sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless-security.key-mgmt wpa-psk
$sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless-security.auth-alg open
$sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless.wake-on-wlan 2
#$sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless-security.psk ${WIFI_PASSWORD}
#$sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless-security.psk password-file 
echo
echo "> Trying to activate the new connection."
echo "> This connection to razpass will propably disconnect."
read -p "< Press enter to continue >"
echo
$sudo nmcli connection up "${WIFI_SSID}" passwd-file "${WIFI_PASSWORD_FILE}"
#rm /home/p/wifi_password


#$sudo nmcli connection up "${WIFI_SSID}" && nmcli connection show
#$sudo nmcli connection up "${WIFI_SSID}" 


