#!/bin/bash
#
# 20240219 Jens Heine <binbash@gmx.net>
#
# Update some scripts in the razpass installation.
#
#set -x
set -e

echo
echo "-------------------------------------"
echo "<<< Updating razpass installation >>>"
echo "-------------------------------------"
echo
read -p "< Press enter to start or ctrl-c to cancel >"
echo

echo ">>> Creating temporary directory..."
cd ~
[ -d tmp ] || mkdir tmp
cd tmp

echo ">>> Cleaning eventually existing old stuff..."
[ -d razpass ] && rm -rf razpass

echo ">>> Cloning razpass project from github..."
git clone https://github.com/binbash23/razpass.git

# some tricky stuff because I will overrwite this script by a new version
# If the git cloning contains this file (which it probably will) I delete
# the running update script to change the inode no, so this script will not
# get confused by getting new contents
[ -f ./razpass/source/home_p_bin/razpass_update ] && rm ~/bin/razpass_update

echo ">>> Copying the p scripts to the bin folder..."
cp -v ./razpass/source/home_p_bin/* ~/bin/

echo "--------------------------"
echo ">>> Update successful! <<<"
echo "--------------------------"

